name: docker

on:
    workflow_call:   

jobs:

  dockert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Dowload a build artifact
      uses: actions/download-artifact@v4
      with: 
        name: programa

    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        username: rsenoi
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        logout: true

    - name: docker build and push
      uses: docker/build-push-action@v6.0.0
      with:
        context: .
        file: ./Dockerfile
        tags: rsenoi/go_ci_teste:${{ github.ref_name }}

        

   