name: docker

on:
    workflow_call:

jobs:

  dockert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Dowload a build artifact
      uses: actions/download-artifact@v4
      with: 
        name: programa
        path:

    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        registry:
        username: rsenoi
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        ecr:
        logout: true

    - name: docker build and push
      uses: docker/build-push-action@v6.0.0
      with:
        add-hosts:
        allow:
        build-args:
        build-contexts:
        builder:
        cache-from:
        cache-to:
        cgroup-parent:
        context: .
        file: ./Dockerfile
        labels:
        load:
        network: 
        no-cache: 
        outputs:
        platforms:
        pull:
        push: true
        secrets:
        secret-files:
        shm-size:
        ssh:
        tags: rsenoi/go_ci_teste:${{ github.ref_name }}
        target:
        ulimit:
        github-token:
        

   